# Generated by Django 3.2.3 on 2021-05-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorText', models.CharField(max_length=150)),
                ('isSolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathDescription', models.CharField(max_length=150)),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeHuntBL.path')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('isRangListAllowed', models.BooleanField(default=False)),
                ('currentPathQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeHuntBL.pathquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=150)),
                ('questionAnswer', models.CharField(max_length=100)),
                ('questionHelpFirst', models.CharField(max_length=150)),
                ('questionHelpSecond', models.CharField(max_length=150)),
                ('qrCode', models.CharField(max_length=150)),
                ('locationHint', models.CharField(max_length=150)),
                ('locationName', models.CharField(max_length=100)),
                ('locationLon', models.DecimalField(decimal_places=7, max_digits=15)),
                ('locationLat', models.DecimalField(decimal_places=7, max_digits=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeHuntBL.city')),
            ],
        ),
        migrations.AddField(
            model_name='pathquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeHuntBL.question'),
        ),
    ]
