# Generated by Django 3.2.3 on 2021-05-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHuntBL', '0002_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentPathQuestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeHuntBL.pathquestion'),
        ),
    ]
