# Generated by Django 3.2.3 on 2021-05-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHuntBL', '0003_alter_user_currentpathquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionHelpFirstUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='questionHelpSecondUsed',
            field=models.BooleanField(default=False),
        ),
    ]
