# Generated by Django 3.2.3 on 2021-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHuntBL', '0004_auto_20210527_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionHelpFirstUsed',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionHelpSecondUsed',
        ),
        migrations.AddField(
            model_name='user',
            name='firstHelpUsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secondHelpUsed',
            field=models.BooleanField(default=False),
        ),
    ]
