# Generated by Django 3.2.3 on 2021-06-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHuntBL', '0008_auto_20210610_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentPathId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CodeHuntBL.path'),
        ),
    ]
